#!/usr/bin/env ruby
# Output the current time in decimal time / metric time.
# Decimal time is a system of time keeping where each day consists of
# ten hours, each hour consists of 100 minutes and each minute consists
# of 100 seconds.

require "date"

decimalHourSeconds = 8640
decimalMinuteSeconds = 86.4

secondsPassed = DateTime.now.to_time.to_i - Date.today.to_time.to_i
decimalHour, secondsPassed = secondsPassed.divmod(decimalHourSeconds)
decimalMinute = secondsPassed / decimalMinuteSeconds

puts "#{'%02d' % decimalHour}:#{'%05.2f' % decimalMinute}"
